import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

export type AppLanguage = "vi" | "en";

const STORAGE_KEY = "nutripath_language";

const mealTrackerEnglishMessages: Record<string, string> = {
  "Nhật Ký Bữa Ăn": "Meal Journal",
  "Dữ liệu lấy từ backend theo ngày bạn chọn": "Data is loaded from the backend for the selected date",
  "Không tải được nhật ký bữa ăn": "Unable to load the meal journal",
  "Không tải được danh sách thực phẩm": "Unable to load the food list",
  "Không tải được dữ liệu món tự nấu": "Unable to load custom meal data",
  "Không lưu được món ăn": "Unable to save this food",
  "Không ước tính được món tự nấu": "Unable to estimate this custom meal",
  "Không lưu được món tự nấu": "Unable to save this custom meal",
  "Không lưu được món cá nhân": "Unable to save this personal meal",
  "Không thêm được món cá nhân đã lưu": "Unable to add the saved personal meal",
  "Xóa món cá nhân \"{name}\" khỏi danh sách đã lưu?": "Remove \"{name}\" from your saved meals?",
  "Không xóa được món cá nhân đã lưu": "Unable to remove the saved personal meal",
  "Không lưu được công thức AI vào bữa ăn": "Unable to add the AI recipe to this meal",
  "Không xóa được món ăn": "Unable to remove this food",
  "Không lưu được lượng nước": "Unable to save water intake",
  "Không lưu được món ăn từ ảnh": "Unable to save the meal from this photo",
  "Vui lòng chọn ảnh JPEG, PNG hoặc WEBP": "Please choose a JPEG, PNG, or WEBP image",
  "Ảnh quá lớn. Vui lòng chọn ảnh dưới 5MB": "The image is too large. Please choose one under 5 MB",
  "Không đọc được ảnh món ăn": "Unable to read the food image",
  "Bạn cần chụp hoặc tải ảnh món ăn trước": "Take or upload a food photo first",
  "Không nhận diện được calo từ ảnh": "Unable to estimate calories from this image",
  "Đang tải nhật ký bữa ăn...": "Loading meal journal...",
  "Không có dữ liệu nhật ký": "No meal journal data",
  "Tự động lưu": "Autosave",
  "Đã lưu tự động": "Autosaved",
  "Lưu thất bại": "Save failed",
  "Gói {tier} đang mở Meal Tracker trong {days} ngày gần nhất": "Your {tier} plan includes the last {days} days in Meal Tracker",
  "Tối đa {items} món mỗi ngày, báo cáo dinh dưỡng {days} ngày{exportSuffix}": "Up to {items} foods per day and {days}-day nutrition analytics{exportSuffix}",
  " và xuất báo cáo.": " with report exports.",
  "món đã dùng hôm nay": "foods used today",
  "Tiêu thụ": "Consumed",
  "Mục tiêu": "Goal",
  "Còn lại": "Remaining",
  "Tiến trình calo hôm nay": "Today's calorie progress",
  "{count} món · {total} / {target} kcal": "{count} foods · {total} / {target} kcal",
  "Chưa có món ăn nào": "No foods added yet",
  "Thêm món ăn": "Add food",
  "AI nhận diện ảnh": "AI image recognition",
  "Chụp món ăn dự đoán calo": "Estimate calories from a photo",
  "SVIP dùng AI Vision và AI Coach hiệu chỉnh theo hồ sơ để dự đoán calo tốt nhất.": "SVIP combines AI Vision and AI Coach with your profile for the best estimate.",
  "Chụp rõ toàn bộ phần ăn, đủ sáng và thêm ghi chú khẩu phần để AI ước lượng chính xác hơn.": "Capture the whole serving in good light and add portion notes for a better estimate.",
  "Ảnh món ăn cần ước lượng calo": "Food photo for calorie estimation",
  "Đổi ảnh món ăn": "Change food photo",
  "Chụp hoặc tải ảnh món ăn": "Take or upload a food photo",
  "JPEG, PNG, WEBP dưới 5MB": "JPEG, PNG, or WEBP under 5 MB",
  "Ghi chú thêm: tô lớn/nhỏ, có sốt, ít cơm, ước lượng gram...": "Add notes: bowl size, sauces, less rice, estimated grams...",
  "Đang phân tích ảnh...": "Analyzing image...",
  "Dự đoán calo từ ảnh": "Estimate calories from image",
  "SVIP đã xử lý đa AI": "Processed by multiple SVIP AI models",
  "Tin cậy": "Confidence",
  "AI đã dùng": "AI used",
  "Tỉ lệ dinh dưỡng": "Nutrition ratio",
  "Nước uống": "Water intake",
  "Mục tiêu {target}ml · còn {remaining}ml": "Goal {target} ml · {remaining} ml remaining",
  "Ghi": "Log",
  "Tổng kết ngày": "Daily summary",
  "Calo tiêu thụ": "Calories consumed",
  "{value} kcal còn lại": "{value} kcal remaining",
  "Mục tiêu: {value}g": "Goal: {value} g",
  "Thêm món ăn - {meal}": "Add food - {meal}",
  "Chọn món có sẵn, nhập món tự nấu hoặc thêm công thức AI đã lưu vào nhật ký.": "Choose a food, enter a custom meal, or add a saved AI recipe to your journal.",
  "Kho món": "Food library",
  "Món tự nấu": "Custom meal",
  "Tìm kiếm thực phẩm...": "Search foods...",
  "Không tìm thấy thực phẩm": "No foods found",
  "Tên món ăn": "Dish name",
  "Ví dụ: Cơm gà áp chảo": "Example: Pan-seared chicken rice",
  "Số phần ăn": "Servings",
  "Cách nấu nếu có": "Cooking method (optional)",
  "Ví dụ: áp chảo ít dầu, luộc, kho, xào...": "Example: pan-seared with less oil, boiled, braised, stir-fried...",
  "Nguyên liệu": "Ingredients",
  "Thêm nguyên liệu": "Add ingredient",
  "Ví dụ: cơm trắng": "Example: white rice",
  "Số lượng nguyên liệu {index}": "Ingredient {index} quantity",
  "Ghi chú: bỏ da, ít dầu...": "Notes: skinless, less oil...",
  "Xóa nguyên liệu {index}": "Remove ingredient {index}",
  "Có thể nhập đơn vị đời thường như 1 chén cơm, 1 muỗng cà phê dầu ăn, 1 quả trứng, 1 miếng ức gà hoặc nhập gram để độ tin cậy cao hơn.": "Use everyday units such as a bowl of rice, a teaspoon of oil, one egg, or a chicken breast piece. Grams provide higher confidence.",
  "Món cá nhân đã lưu": "Saved personal meals",
  "Xóa món cá nhân {name}": "Remove personal meal {name}",
  "Ước tính nhanh: {dish} thường khoảng {min}-{max} kcal/phần. Độ tin cậy: {confidence}.": "Quick estimate: {dish} is usually around {min}-{max} kcal per serving. Confidence: {confidence}.",
  "Nguyên liệu trống": "Unnamed ingredient",
  "Độ tin cậy": "Confidence",
  "kcal/phần": "kcal/serving",
  "Đã lưu món này": "Meal saved",
  "Lưu món này": "Save this meal",
  "Chỉnh sửa nguyên liệu": "Edit ingredients",
  "Thêm vào bữa": "Add to meal",
  "Logic: app quy đổi đơn vị đời thường sang gram, sau đó tính Calories = gram × kcal/100g / 100. Kết quả luôn là ước tính và có thể dao động theo cách nấu thực tế.": "The app converts everyday units to grams, then calculates Calories = grams × kcal/100 g / 100. Results are estimates and may vary with the actual cooking method.",
  "Đang tính...": "Calculating...",
  "Tính calo món tự nấu": "Calculate custom meal calories",
  "Chưa có công thức AI đã lưu": "No saved AI recipes yet",
  "Tạo công thức ở trang Công Thức, sau đó quay lại đây để thêm vào nhật ký.": "Create a recipe on the Recipes page, then return here to add it to your journal.",
  "phần tự nấu": "custom serving",
  "phần": "serving",
  "phút": "min",
  "Công thức AI": "AI recipes",
  "Bữa sáng": "Breakfast",
  "Bữa trưa": "Lunch",
  "Bữa tối": "Dinner",
  "Bữa phụ": "Snacks",
  "Chén": "Bowl",
  "Bát": "Bowl",
  "Muỗng cà phê": "Teaspoon",
  "Muỗng canh": "Tablespoon",
  "Quả": "Piece",
  "Miếng": "Piece",
  "Lát": "Slice",
  "Tô": "Large bowl",
};

const svipEnglishMessages: Record<string, string> = {
  "Miễn phí": "Free",
  "Bắt đầu nhẹ nhàng": "A simple start",
  "Người mới muốn tính calo, thử nhật ký bữa ăn và làm quen với NutriPath.": "New users who want to calculate calories, try meal tracking, and get familiar with NutriPath.",
  "Tính BMR, TDEE và mục tiêu calo cơ bản.": "Calculate BMR, TDEE, and a basic calorie goal.",
  "Truy cập công thức mẫu để bắt đầu ăn healthy.": "Access starter recipes for healthier eating.",
  "Ghi nhật ký bữa ăn ở mức cơ bản.": "Use the basic meal journal.",
  "AI chat giới hạn cho câu hỏi dinh dưỡng nhanh.": "Limited AI chat for quick nutrition questions.",
  "Dùng miễn phí": "Use for free",
  "Phổ biến nhất": "Most popular",
  "Đề xuất": "Recommended",
  "Người nghiêm túc theo dõi calo mỗi ngày và muốn nhiều công thức, báo cáo hơn.": "People who track calories daily and want more recipes and reports.",
  "Theo dõi calo và bữa ăn không giới hạn.": "Unlimited calorie and meal tracking.",
  "Mở khóa kho công thức Việt phong phú hơn.": "Unlock a richer Vietnamese recipe library.",
  "Nhiều lượt AI chat dinh dưỡng mỗi ngày.": "More nutrition AI chats every day.",
  "Báo cáo tiến trình và macro chi tiết hơn.": "More detailed progress and macro reports.",
  "Trải nghiệm sạch hơn, ưu tiên tính năng nâng cao.": "A cleaner experience with priority access to advanced features.",
  "Nâng cấp VIP": "Upgrade to VIP",
  "Cao cấp nhất": "Highest tier",
  "Người cần huấn luyện cá nhân hóa sâu, AI Coach riêng và hỗ trợ ưu tiên.": "People who need deep personalization, a dedicated AI Coach, and priority support.",
  "Bao gồm toàn bộ quyền lợi VIP.": "Includes every VIP benefit.",
  "AI Coach dinh dưỡng cá nhân hóa theo mục tiêu.": "Nutrition AI Coach personalized to your goals.",
  "Thực đơn tùy chỉnh theo khẩu vị, lịch sinh hoạt và mục tiêu.": "Meal plans tailored to your taste, schedule, and goals.",
  "AI chat không giới hạn và phản hồi ưu tiên.": "Unlimited AI chat with priority responses.",
  "Phân tích tiến trình, macro và thói quen chuyên sâu.": "Advanced progress, macro, and habit analysis.",
  "Hỗ trợ ưu tiên 24/7 cho hành trình sức khỏe.": "24/7 priority support for your health journey.",
  "Khám phá SVIP": "Explore SVIP",
  "Tính calo, BMR, TDEE": "Calories, BMR, and TDEE",
  "Nhật ký bữa ăn": "Meal journal",
  "Cơ bản": "Basic",
  "Không giới hạn": "Unlimited",
  "Không giới hạn + gợi ý tối ưu": "Unlimited + optimized suggestions",
  "Kho công thức": "Recipe library",
  "Giới hạn": "Limited",
  "Mở rộng": "Expanded",
  "Mở rộng + độc quyền": "Expanded + exclusive",
  "AI chat dinh dưỡng": "Nutrition AI chat",
  "Nhiều lượt/ngày": "More chats/day",
  "AI Coach cá nhân": "Personal AI Coach",
  "Báo cáo chuyên sâu": "Advanced reports",
  "Hỗ trợ ưu tiên 24/7": "24/7 priority support",
  "Không tải được dữ liệu gói.": "Unable to load plan data.",
  "Gói thành viên NutriPath": "NutriPath membership",
  "Chọn lộ trình sức khỏe phù hợp với bạn": "Choose the health journey that fits you",
  "Free để bắt đầu, VIP để theo dõi nghiêm túc, SVIP để có AI Coach cá nhân hóa sâu. Cả ba gói đều được đồng bộ từ dữ liệu thành viên hiện tại.": "Start with Free, track seriously with VIP, or choose SVIP for deep AI Coach personalization. All three plans stay synced with your current membership data.",
  "Free cho người mới": "Free for beginners",
  "VIP cho theo dõi hằng ngày": "VIP for daily tracking",
  "SVIP cho cá nhân hóa sâu": "SVIP for deep personalization",
  "AI Coach cao cấp": "Premium AI Coach",
  "3 lựa chọn": "3 options",
  "SVIP từ": "SVIP from",
  "Thanh toán": "Billing",
  "Tài khoản": "Account",
  "Đã đăng nhập": "Signed in",
  "Khách": "Guest",
  "tháng": "month",
  "Theo năm": "Annual",
  "SVIP không thay thế Free hay VIP. Trang này giúp bạn nhìn rõ từng cấp quyền lợi để chọn đúng gói trước khi nâng cấp.": "SVIP does not replace Free or VIP. This page explains each benefit tier so you can choose the right plan before upgrading.",
  "SO SÁNH 3 GÓI": "COMPARE 3 PLANS",
  "Quyền lợi rõ ràng cho từng nhu cầu": "Clear benefits for every need",
  "Giá và tên gói lấy từ backend; phần mô tả bên dưới giải thích cụ thể bạn nhận được gì ở Free, VIP và SVIP.": "Plan names and prices come from the backend; the details below explain exactly what Free, VIP, and SVIP include.",
  "Theo tháng": "Monthly",
  "Theo năm -20%": "Annual -20%",
  "Thanh toán năm, tiết kiệm 20% so với tháng.": "Pay annually and save 20% versus monthly billing.",
  "BẢNG QUYỀN LỢI": "BENEFIT TABLE",
  "Free, VIP và SVIP khác nhau ở đâu?": "How are Free, VIP, and SVIP different?",
  "Tính năng": "Feature",
  "Muốn cá nhân hóa sâu hơn?": "Want deeper personalization?",
  "Bắt đầu miễn phí, nâng lên VIP khi bạn cần theo dõi đều đặn, hoặc chọn SVIP khi muốn AI Coach đồng hành như một chuyên gia riêng.": "Start free, upgrade to VIP for consistent tracking, or choose SVIP when you want AI Coach to work like a personal expert.",
  "Chọn SVIP": "Choose SVIP",
  "Xem trang gói thành viên": "View membership plans",
};

const assistantEnglishMessages: Record<string, string> = {
  "Xin chào! Tôi là NutriBot. Tôi có thể giúp bạn tính calo, gợi ý món ăn và xây dựng thói quen ăn uống lành mạnh.": "Hello! I'm NutriBot. I can help you calculate calories, suggest meals, and build healthier eating habits.",
  "Tôi chưa nhận được phản hồi từ hệ thống.": "I did not receive a response from the system.",
  "Không thể kết nối đến NutriBot. Vui lòng thử lại.": "Unable to connect to NutriBot. Please try again.",
  "Trình duyệt hiện chưa hỗ trợ ghi âm. Bạn có thể nhập tin nhắn bằng bàn phím.": "Your browser does not support voice input. You can type your message instead.",
  "Mình chưa nghe rõ. Bạn thử nói lại hoặc nhập bằng bàn phím nhé.": "I couldn't hear that clearly. Please try again or type your message.",
  "Cá nhân hóa theo hồ sơ": "Personalized to your profile",
  "Đang hoạt động": "Online",
  "Đóng cửa sổ NutriBot": "Close NutriBot window",
  "NutriBot thường": "Standard NutriBot",
  "SVIP mở AI Coach cá nhân hóa theo hồ sơ, nhật ký bữa ăn và mục tiêu của bạn.": "SVIP unlocks AI Coach personalization using your profile, meal journal, and goals.",
  "Đóng thông báo lỗi": "Dismiss error",
  "Nhắn mục tiêu hoặc vấn đề dinh dưỡng của bạn...": "Tell AI Coach about your goal or nutrition concern...",
  "Nhắn tin cho NutriBot...": "Message NutriBot...",
  "Tin nhắn cho AI Coach": "Message for AI Coach",
  "Tin nhắn cho NutriBot": "Message for NutriBot",
  "Đang nghe": "Listening",
  "Ghi âm": "Voice input",
  "Đang nghe...": "Listening...",
  "Ghi âm bằng ngôn ngữ đã chọn": "Voice input in the selected language",
  "Gửi tin nhắn": "Send message",
  "Nhập bằng giọng nói": "Voice input",
  "Trình duyệt chưa hỗ trợ nhập giọng nói": "Voice input is not supported by this browser",
  "Theo dõi calo không giới hạn": "Unlimited calorie tracking",
  "50 tin nhắn AI mỗi ngày": "50 AI messages per day",
  "Toàn bộ kho công thức Việt": "Full Vietnamese recipe library",
  "Không quảng cáo, trải nghiệm sạch": "Ad-free experience",
  "AI Coach dinh dưỡng cá nhân riêng": "Personal nutrition AI Coach",
  "Thực đơn tùy chỉnh hoàn toàn": "Fully customized meal plans",
  "Phân tích thành phần cơ thể": "Body composition analysis",
  "Đóng cửa sổ nâng cấp": "Close upgrade window",
  "Nâng cấp lên {plan}": "Upgrade to {plan}",
  "Mở khóa toàn bộ công thức, AI chat và trải nghiệm không quảng cáo": "Unlock every recipe, AI chat, and an ad-free experience",
  "Trải nghiệm đỉnh cao với AI Coach dinh dưỡng hoàn toàn cá nhân hóa": "Get the premium experience with a fully personalized nutrition AI Coach",
  "Thanh toán hàng tháng": "Monthly billing",
  "7 ngày dùng thử miễn phí": "7-day free trial",
  "Nâng cấp ngay": "Upgrade now",
  "Dùng thử 7 ngày miễn phí": "Start a 7-day free trial",
  "Bảo mật SSL": "SSL secured",
  "Kích hoạt ngay": "Instant activation",
  "Hủy mọi lúc": "Cancel anytime",
};

const adminEnglishMessages: Record<string, string> = {
  "Không tải được tổng quan admin.": "Unable to load the admin overview.",
  "Không tải được danh sách người dùng.": "Unable to load the user list.",
  "Không tải được dữ liệu thanh toán.": "Unable to load payment data.",
  "Không tải được nội dung hệ thống.": "Unable to load system content.",
  "Không cập nhật được món ăn.": "Unable to update the food item.",
  "Không thêm được món ăn mới.": "Unable to add the new food item.",
  "Không lưu được người dùng.": "Unable to save the user.",
  "Xóa món ăn này khỏi hệ thống?": "Delete this food item from the system?",
  "Không xóa được món ăn.": "Unable to delete the food item.",
  "Không tải được analytics.": "Unable to load analytics.",
  "Không tải được cài đặt AI.": "Unable to load AI settings.",
  "Không tải được bảo mật hệ thống.": "Unable to load security settings.",
  "Không lưu được cài đặt AI.": "Unable to save AI settings.",
  "Không lưu được cấu hình bảo mật.": "Unable to save security settings.",
  "Admin Dashboard": "Admin Dashboard",
  "Quản trị hệ thống NutriPath": "NutriPath system administration",
  "Dữ liệu thật cho người dùng, thanh toán, nội dung, analytics, AI và bảo mật.": "Live data for users, payments, content, analytics, AI, and security.",
  "Làm mới tab": "Refresh tab",
  "Đang tải dữ liệu tổng quan...": "Loading overview data...",
  "Người dùng mới nhất": "Newest users",
  "8 tài khoản gần đây từ dữ liệu member thật": "The 8 most recent accounts from live member data",
  "Mở tab người dùng": "Open users tab",
  "Tham gia {date}": "Joined {date}",
  "Phân bổ vai trò": "Role distribution",
  "Phân bổ gói": "Plan distribution",
  "Tình trạng dịch vụ": "Service status",
  "Bảng người dùng": "Users table",
  "Lấy trực tiếp từ member thật trong hệ thống": "Loaded directly from live members in the system",
  "Admin hiện tại: {email}": "Current admin: {email}",
  "Tìm theo tên hoặc email": "Search by name or email",
  "Sửa người dùng: {name}": "Edit user: {name}",
  "Cập nhật role, trạng thái, gói và mục tiêu calo bằng dữ liệu thật.": "Update role, status, plan, and calorie goal using live data.",
  "Hủy": "Cancel",
  "Tên": "Name",
  "Tạm ngưng": "Inactive",
  "Chu kỳ": "Billing cycle",
  "Tháng": "Month",
  "Năm": "Year",
  "Mục tiêu calo": "Calorie goal",
  "Đang tải bảng người dùng...": "Loading users table...",
  "{count} người dùng khớp bộ lọc hiện tại": "{count} users match the current filters",
  "Dữ liệu thật, không dùng mảng mock": "Live data, no mock arrays",
  "Người dùng": "Users",
  "Vai trò": "Role",
  "Tham gia": "Joined",
  "Thao tác": "Actions",
  "Sửa": "Edit",
  "Đang tải dữ liệu thanh toán...": "Loading payment data...",
  "Doanh thu đã xác nhận": "Confirmed revenue",
  "{count} giao dịch đã thanh toán": "{count} paid transactions",
  "Tổng giao dịch": "Total transactions",
  "{count} lượt dùng thử": "{count} trials",
  "Đang chờ IPN": "Awaiting IPN",
  "Chưa kích hoạt quyền thành viên": "Membership access has not been activated",
  "Giao dịch thất bại": "Failed transactions",
  "Không được tính vào doanh thu": "Excluded from revenue",
  "Dữ liệu thật từ payments; trạng thái trả phí chỉ do IPN VNPAY xác nhận": "Live payment data; paid status is confirmed only by the VNPAY IPN.",
  "Tìm email, hóa đơn hoặc mã giao dịch": "Search email, invoice, or transaction ID",
  "Mọi trạng thái": "All statuses",
  "Đã thanh toán": "Paid",
  "Đang chờ": "Pending",
  "Thất bại": "Failed",
  "Dùng thử": "Trial",
  "Mọi gói": "All plans",
  "Đang cập nhật danh sách giao dịch...": "Updating transaction list...",
  "Giao dịch": "Transaction",
  "Người mua": "Customer",
  "Cổng": "Gateway",
  "Không có mã VNPAY": "No VNPAY reference",
  "Tài khoản không còn tồn tại": "Account no longer exists",
  "Không có giao dịch phù hợp bộ lọc.": "No transactions match the filters.",
  "{count} giao dịch • Trang {page}/{totalPages}": "{count} transactions • Page {page}/{totalPages}",
  "Trang trước": "Previous page",
  "Trang sau": "Next page",
  "Đang tải nội dung...": "Loading content...",
  "Foods": "Foods",
  "Nguồn dữ liệu hiện có": "Available data source",
  "Recipes": "Recipes",
  "Công thức đang publish": "Published recipes",
  "Meal plans": "Meal plans",
  "Kế hoạch/quyền lợi gói": "Plan schedules and benefits",
  "Tên món": "Food name",
  "Ức gà áp chảo": "Pan-seared chicken breast",
  "Danh mục": "Category",
  "Khẩu phần": "Serving",
  "100g / 1 bát / 1 ly": "100 g / 1 bowl / 1 glass",
  "Hủy sửa": "Cancel editing",
  "10 thực phẩm đầu tiên từ database": "First 10 food items from the database",
  "Xóa": "Delete",
  "10 công thức đầu tiên từ hệ thống": "First 10 recipes in the system",
  "{minutes} phút • {servings} khẩu phần": "{minutes} min • {servings} servings",
  "Meal plans / quyền lợi gói": "Meal plans / plan benefits",
  "Đang lấy từ plans thực tế của hệ thống": "Loaded from the system's live plans",
  "Giá/tháng": "Monthly price",
  "Đang tải analytics...": "Loading analytics...",
  "Meal activity 7 ngày": "7-day meal activity",
  "Tổng số món được ghi nhận mỗi ngày": "Total meals logged each day",
  "Tỷ lệ macro": "Macro distribution",
  "Tổng hợp từ meal log thực tế": "Aggregated from live meal logs",
  "Top món được ghi nhận": "Most logged dishes",
  "Sắp xếp theo số lần xuất hiện trong meal log": "Ranked by frequency in meal logs",
  "lần ghi nhận": "logs",
  "Đang tải cài đặt AI...": "Loading AI settings...",
  "Cài đặt AI": "AI settings",
  "Đang lưu vào backend settings hiện tại": "Saved to the current backend settings",
  "Tự động gợi ý khẩu phần.": "Automatically recommend serving sizes.",
  "Bật gợi ý bữa ăn thông minh.": "Enable smart meal suggestions.",
  "Kiểm tra chéo logic dinh dưỡng.": "Cross-check nutrition logic.",
  "Đang tải cấu hình bảo mật...": "Loading security settings...",
  "Cài đặt bảo mật": "Security settings",
  "Quản lý policy và theo dõi hoạt động đăng nhập": "Manage policies and monitor login activity",
  "Bật/tắt xác thực hai lớp cho admin flow.": "Enable or disable two-factor authentication for admin flows.",
  "Password policy": "Password policy",
  "Độ dài tối thiểu": "Minimum length",
  "Ký tự đặc biệt": "Special character",
  "Chữ hoa": "Uppercase letter",
  "Chữ số": "Number",
  "Login activity": "Login activity",
  "Lấy từ security settings hiện tại": "Loaded from the current security settings",
  "AI safety logs": "AI safety logs",
  "Nhật ký prompt nguy hiểm để admin kiểm tra": "Dangerous prompt logs for administrator review",
  "Không có prompt.": "No prompt available.",
  "Chưa có safety log nào.": "No safety logs yet.",
  "Nội dung": "Content",
  "Analytics": "Analytics",
  "AI": "AI",
};

const englishMessages: Record<string, string> = {
  ...mealTrackerEnglishMessages,
  ...svipEnglishMessages,
  ...assistantEnglishMessages,
  ...adminEnglishMessages,
  "Dashboard": "Dashboard",
  "Tính Calo": "Calorie Calculator",
  "Theo Dõi": "Tracker",
  "Công Thức": "Recipes",
  "Báo cáo": "Reports",
  "Gói thành viên": "Membership",
  "Admin": "Admin",
  "Thông báo": "Notifications",
  "Đánh dấu đã đọc": "Mark all as read",
  "Chưa có thông báo mới.": "No new notifications.",
  "Đăng nhập": "Log in",
  "Đăng ký": "Sign up",
  "Đăng xuất": "Log out",
  "Mở thông báo": "Open notifications",
  "Mở NutriBot": "Open NutriBot",
  "Đóng NutriBot": "Close NutriBot",
  "Tiếng Việt": "Vietnamese",
  "Tiếng Anh": "English",
  "Chuyển sang tiếng Anh": "Switch to English",
  "Chuyển sang tiếng Việt": "Switch to Vietnamese",
  "Theo dõi dinh dưỡng bằng dữ liệu thật của bạn.": "Track your nutrition with your real data.",
  "Đăng nhập để dashboard, nhật ký bữa ăn và hồ sơ thành viên lấy đúng dữ liệu từ SQL theo tài khoản hiện tại.": "Log in to access your personal dashboard, meal journal, and member profile data.",
  "Dùng email và mật khẩu đã đăng ký để vào dữ liệu cá nhân.": "Use your registered email and password to access your personal data.",
  "Mật khẩu": "Password",
  "Quên mật khẩu?": "Forgot password?",
  "Đang đăng nhập...": "Logging in...",
  "Không đăng nhập được.": "Unable to log in.",
  "Không đăng nhập được bằng mạng xã hội.": "Unable to log in with this social account.",
  "hoặc": "or",
  "Chưa có tài khoản?": "Don't have an account?",
  "Đăng ký ngay": "Sign up now",
  "Đang mở Google...": "Opening Google...",
  "Đang mở Facebook...": "Opening Facebook...",
  "Đang chuyển đến {provider}...": "Redirecting to {provider}...",
  "Cần cấu hình VITE_SUPABASE_URL và VITE_SUPABASE_ANON_KEY để bật Google/Facebook.": "Configure VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to enable Google/Facebook.",
  "Tạo tài khoản để lưu hồ sơ và nhật ký dinh dưỡng trên SQL.": "Create an account to save your profile and nutrition journal.",
  "Họ tên": "Full name",
  "Mục tiêu": "Goal",
  "Giảm cân": "Lose weight",
  "Giữ cân": "Maintain weight",
  "Tăng cơ": "Build muscle",
  "Ít nhất 6 ký tự": "At least 6 characters",
  "Xác nhận mật khẩu": "Confirm password",
  "Nhập lại mật khẩu": "Re-enter your password",
  "Mật khẩu xác nhận chưa khớp.": "Password confirmation does not match.",
  "Không tạo được tài khoản.": "Unable to create the account.",
  "Không đăng ký được bằng mạng xã hội.": "Unable to sign up with this social account.",
  "Đang tạo tài khoản...": "Creating account...",
  "Tạo tài khoản": "Create account",
  "Xác minh email": "Verify your email",
  "Nhập mã OTP đã gửi đến": "Enter the OTP sent to",
  "Mã OTP": "OTP code",
  "Mã OTP phải gồm từ 6 đến 8 chữ số.": "The OTP must contain 6 to 8 digits.",
  "Không xác minh được mã OTP.": "Unable to verify the OTP.",
  "Đã gửi lại mã OTP. Hãy kiểm tra hộp thư của bạn.": "A new OTP was sent. Please check your inbox.",
  "Không gửi lại được mã OTP.": "Unable to resend the OTP.",
  "Đang xác minh...": "Verifying...",
  "Đổi email": "Change email",
  "Gửi lại sau {seconds}s": "Resend in {seconds}s",
  "Gửi lại OTP": "Resend OTP",
  "Xác minh và tạo tài khoản": "Verify and create account",
  "Xác minh mã OTP": "Verify OTP",
  "Đang gửi mã OTP...": "Sending OTP...",
  "Gửi mã OTP": "Send OTP",
  "Không gửi được mã OTP.": "Unable to send the OTP.",
  "Mục đích OTP không hợp lệ.": "Invalid OTP purpose.",
  "Email không hợp lệ.": "Invalid email address.",
  "Email này đã có tài khoản đăng nhập.": "An account already exists for this email.",
  "Backend chưa cấu hình Supabase Email OTP.": "Supabase Email OTP is not configured on the backend.",
  "Không kết nối được Supabase Email OTP.": "Unable to connect to Supabase Email OTP.",
  "Mã OTP không khớp với email cần xác minh.": "The OTP does not match the email being verified.",
  "Mã OTP không hợp lệ hoặc đã hết hạn.": "The OTP is invalid or has expired.",
  "Phiên xác minh OTP không hợp lệ hoặc đã hết hạn.": "The OTP verification session is invalid or has expired.",
  "Không thể đặt lại mật khẩu cho tài khoản này.": "The password cannot be reset for this account.",
  "Mật khẩu cần ít nhất 6 ký tự.": "The password must contain at least 6 characters.",
  "Quên mật khẩu": "Forgot password",
  "Nhập email đã đăng ký để nhận mã OTP đặt lại mật khẩu.": "Enter your registered email to receive a password reset OTP.",
  "Tạo mật khẩu mới": "Create a new password",
  "Email đã được xác minh. Hãy đặt mật khẩu mới cho tài khoản.": "Your email is verified. Set a new password for your account.",
  "Mật khẩu mới": "New password",
  "Hiện hoặc ẩn mật khẩu": "Show or hide password",
  "Không đặt lại được mật khẩu.": "Unable to reset the password.",
  "Đang cập nhật...": "Updating...",
  "Đặt lại mật khẩu": "Reset password",
  "Đổi mật khẩu thành công": "Password changed successfully",
  "Bạn có thể đăng nhập bằng mật khẩu mới ngay bây giờ.": "You can now sign in with your new password.",
  "Đã có tài khoản?": "Already have an account?",
  "Mỗi tài khoản có hồ sơ, mục tiêu và dữ liệu riêng.": "Every account has its own profile, goals, and data.",
  "Khi đăng ký, backend tạo member thật và credential thật. Website sẽ dùng session để gọi API theo đúng người đang đăng nhập.": "When you sign up, NutriPath creates a real member profile and secure credentials for your personal session.",
  "Không nhận được phiên đăng nhập từ Supabase.": "No login session was received from Supabase.",
  "Không hoàn tất đăng nhập bằng mạng xã hội.": "Unable to complete social login.",
  "Hết thời gian xác thực (30 giây). Vui lòng thử lại.": "Authentication timed out after 30 seconds. Please try again.",
  "Đang tải thông tin đăng nhập...": "Loading login information...",
  "Đang xác thực tài khoản Google/Facebook...": "Verifying your Google/Facebook account...",
  "Đang đồng bộ hồ sơ cá nhân...": "Syncing your personal profile...",
  "Đã xảy ra lỗi không xác định.": "An unknown error occurred.",
  "Không hoàn tất đăng nhập": "Login could not be completed",
  "Đang hoàn tất đăng nhập": "Completing login",
  "Thử lại": "Try again",
  "Quay lại đăng nhập": "Back to login",
  "Tính Calo Thông Minh": "Smart Calorie Calculator",
  "Tính BMR, TDEE và nhu cầu dinh dưỡng cá nhân hóa theo mục tiêu của bạn": "Calculate BMR, TDEE, and personalized nutrition needs for your goals",
  "TDEE hôm nay": "Today's TDEE",
  "AI Chatbot Dinh Dưỡng": "AI Nutrition Chatbot",
  "Trò chuyện với AI chuyên gia 24/7, nhận tư vấn dinh dưỡng cá nhân hóa tức thì": "Chat with an AI nutrition assistant 24/7 for instant personalized guidance",
  "Tôi muốn ăn gì tốt cho sức khỏe? 🥗": "What should I eat for better health? 🥗",
  "Gợi ý: Cháo gà + rau muống xào... ✨": "Suggestion: Chicken congee with stir-fried greens... ✨",
  "Kho Công Thức Healthy": "Healthy Recipe Library",
  "Hàng trăm công thức nấu ăn lành mạnh với hướng dẫn chi tiết từng bước": "Hundreds of healthy recipes with detailed step-by-step instructions",
  "Cháo Gà Gừng": "Ginger Chicken Congee",
  "Cơm Tấm Sườn Nướng": "Grilled Pork Broken Rice",
  "Nhật Ký Bữa Ăn": "Meal Journal",
  "Ghi lại từng bữa ăn, theo dõi calo và dinh dưỡng hàng ngày dễ dàng": "Log every meal and easily track daily calories and nutrition",
  "Bữa sáng": "Breakfast",
  "Bữa trưa": "Lunch",
  "Bữa tối": "Dinner",
  "Tạo hồ sơ sức khỏe": "Create your health profile",
  "Nhập thông tin cơ bản: chiều cao, cân nặng, tuổi và mục tiêu sức khỏe của bạn.": "Enter your height, weight, age, and health goals.",
  "AI phân tích & tư vấn": "AI analysis and guidance",
  "Hệ thống AI tính toán nhu cầu dinh dưỡng và lên kế hoạch ăn uống phù hợp.": "AI calculates your nutrition needs and creates a suitable meal plan.",
  "Theo dõi & cải thiện": "Track and improve",
  "Ghi lại bữa ăn hàng ngày và nhận báo cáo tiến trình chi tiết mỗi tuần.": "Log daily meals and receive detailed weekly progress reports.",
  "Miễn phí": "Free",
  "Bắt đầu hành trình sức khỏe": "Start your health journey",
  "Tính calo & BMR cơ bản": "Basic calorie and BMR calculation",
  "50+ công thức món Việt": "50+ Vietnamese recipes",
  "Nhật ký bữa ăn cơ bản": "Basic meal journal",
  "Dùng miễn phí": "Use for free",
  "Phổ biến nhất": "Most popular",
  "Cho người nghiêm túc với sức khỏe": "For people serious about their health",
  "/tháng": "/month",
  "AI chatbot dinh dưỡng 24/7": "24/7 AI nutrition chatbot",
  "200+ công thức độc quyền": "200+ exclusive recipes",
  "Báo cáo tiến trình chi tiết": "Detailed progress reports",
  "Nâng cấp VIP": "Upgrade to VIP",
  "🔥 PHỔ BIẾN": "🔥 POPULAR",
  "Cao cấp nhất": "Top tier",
  "Trải nghiệm đỉnh cao, không giới hạn": "Premium experience without limits",
  "Tư vấn 1-1 chuyên gia dinh dưỡng": "One-on-one nutrition expert guidance",
  "AI cá nhân hóa tuyệt đối": "Fully personalized AI",
  "Toàn bộ tính năng không giới hạn": "Unlimited access to every feature",
  "Khám phá SVIP": "Explore SVIP",
  "Trợ lý dinh dưỡng AI #1 Việt Nam": "Vietnam's leading AI nutrition assistant",
  "Ăn Healthy —": "Eat Healthy —",
  "Sống Khỏe": "Live Well",
  "Mỗi Ngày": "Every Day",
  "NutriPath là trợ lý dinh dưỡng thông minh giúp bạn tính toán calo, lên kế hoạch bữa ăn và đạt mục tiêu sức khỏe với sự hỗ trợ của trí tuệ nhân tạo.": "NutriPath is an intelligent nutrition assistant that helps you calculate calories, plan meals, and reach your health goals with AI support.",
  "Bắt Đầu Miễn Phí": "Start for Free",
  "Xem Demo": "View Demo",
  "Dùng thử 14 ngày miễn phí": "14-day free trial",
  "Không cần thẻ tín dụng": "No credit card required",
  "Hủy bất cứ lúc nào": "Cancel anytime",
  "Tiến trình tuần này": "This week's progress",
  "Hôm nay": "Today",
  "Tính năng nổi bật": "Featured capabilities",
  "Mọi thứ bạn cần để": "Everything you need to",
  "sống khỏe hơn": "live healthier",
  "Từ tính toán dinh dưỡng đến gợi ý công thức — NutriPath là người bạn đồng hành hoàn hảo trên hành trình sức khỏe.": "From nutrition calculations to recipe suggestions, NutriPath supports every step of your health journey.",
  "Khám phá ngay": "Explore now",
  "Cách thức hoạt động": "How it works",
  "Bắt đầu chỉ trong": "Get started in",
  "3 bước đơn giản": "3 simple steps",
  "Hệ thống thành viên": "Membership plans",
  "Chọn hành trình": "Choose the journey",
  "phù hợp": "that fits",
  "với bạn": "you",
  "Từ người mới bắt đầu đến chuyên gia sức khỏe — NutriPath có gói thành viên dành riêng cho mọi mục tiêu và lối sống.": "From beginners to dedicated wellness enthusiasts, NutriPath has a plan for every goal and lifestyle.",
  "Và nhiều tính năng miễn phí khác": "And many more free features",
  "15+ tính năng nâng cao độc quyền": "15+ exclusive advanced features",
  "Toàn bộ tính năng + ưu tiên tuyệt đối": "Every feature with top priority",
  "Chưa chắc chắn gói nào phù hợp?": "Not sure which plan fits?",
  "So sánh đầy đủ tính năng và lợi ích của từng gói thành viên": "Compare all features and benefits across membership plans",
  "So sánh tất cả gói": "Compare all plans",
  "Bắt đầu hành trình": "Start your journey to",
  "sống khỏe ngay hôm nay!": "better health today!",
  "Tham gia NutriPath ngay hôm nay và trải nghiệm 14 ngày miễn phí!": "Join NutriPath today and enjoy a 14-day free trial!",
  "Dùng Thử Miễn Phí": "Start Free Trial",
  "Dùng thử 14 ngày • Không cần thẻ tín dụng": "14-day free trial • No credit card required",
  "Tất cả quyền được bảo lưu.": "All rights reserved.",
  "Điều khoản": "Terms",
  "Bảo mật": "Privacy",
  "Liên hệ": "Contact",
  "Nguyễn Minh An": "Alex Nguyen",
  "Thêm bữa ăn": "Add meal",
  "Chat với AI": "Chat with AI",
  "Tìm công thức": "Find recipes",
  "Đang tải dữ liệu dashboard...": "Loading dashboard data...",
  "Không có dữ liệu dashboard": "Dashboard data is unavailable",
  "Dữ liệu được tải từ backend": "Data loaded from the backend",
  "Protein": "Protein",
  "Carbs": "Carbs",
  "Chất béo": "Fat",
  "Calo hôm nay": "Today's calories",
  "mục tiêu": "of goal",
  "kcal còn lại": "kcal remaining",
  "kcal đã đốt": "kcal burned",
  "Dinh dưỡng đa lượng": "Macronutrients",
  "Nhật ký bữa ăn hôm nay": "Today's meal journal",
  "Xem tất cả": "View all",
  "Hôm nay chưa có bữa ăn nào": "No meals logged today",
  "Thêm món ở Meal Tracker để dashboard cập nhật calo, macro và tiến trình tuần theo dữ liệu thật.": "Add food in Meal Tracker to update calories, macros, and weekly progress using your real data.",
  "+ Thêm": "+ Add",
  "Hoạt động thể chất": "Physical activity",
  "Nhập bài tập để hệ thống ước tính calo đã dùng.": "Log a workout so NutriPath can estimate calories burned.",
  "Đi bộ": "Walking",
  "Đốt cháy": "Burned",
  "Thời gian": "Time",
  "bước": "steps",
  "phút": "minutes",
  "Lượng nước": "Water intake",
  "mục tiêu hôm nay": "of today's goal",
  "đang đồng bộ": "syncing",
  "Lượng nước muốn thêm": "Water amount to add",
  "Ghi": "Log",
  "Theo dõi cân nặng": "Weight tracking",
  "hiện tại": "current",
  "Net hôm nay": "Today's net",
  "Calo in {caloriesIn} - mục tiêu {calorieTarget} - calo out {caloriesOut}. Nếu giữ nhịp này 7 ngày, cân nặng có thể {direction} khoảng {delta}kg.": "Calories in {caloriesIn} - target {calorieTarget} - calories out {caloriesOut}. At this pace for 7 days, weight may {direction} by about {delta} kg.",
  "tăng": "increase",
  "giảm": "decrease",
  "Tiến trình tuần": "Weekly progress",
  "Thực tế": "Actual",
  "Báo cáo theo gói {tier}": "{tier} plan reports",
  "Mở lịch sử và phân tích trong {days} ngày{exportSuffix}": "Access history and analytics for {days} days{exportSuffix}",
  ", có xuất báo cáo.": ", with report exports.",
  ".": ".",
  "Thành tích": "Achievements",
  "Mục tiêu hôm nay": "Today's goals",
  "Mẹo hôm nay": "Today's tip",
  "Kế hoạch tuần": "Weekly plan",
  "Đang tạo...": "Generating...",
  "Tạo lại kế hoạch": "Regenerate plan",
  "Tạo kế hoạch 7 ngày": "Create a 7-day plan",
  "Tạo kế hoạch 7 ngày dựa trên mục tiêu calo, macro và nhật ký bữa ăn gần nhất.": "Create a 7-day plan based on your calorie target, macros, and recent meal journal.",
  "AI Coach chỉ dành cho SVIP": "AI Coach is available to SVIP members only",
  "Nâng cấp để tạo kế hoạch ăn uống 7 ngày cá nhân hóa.": "Upgrade to create a personalized 7-day meal plan.",
  "Mở SVIP": "Explore SVIP",
  "Thấp": "Low",
  "Trung bình": "Medium",
  "Cao": "High",
  "Tự nhập": "Manual",
  "Bài tập đã ghi hôm nay": "Today's workouts",
  "{count} mục": "{count} entries",
  "Chưa có bài tập nào hôm nay": "No workouts logged today",
  "Ghi đạp xe, chạy bộ, chạy máy có dốc, tập gym hoặc bài khác để dashboard tính calo đã đốt.": "Log cycling, running, incline treadmill, gym, or another activity to calculate calories burned.",
  "dốc": "incline",
  "Xóa {label}": "Delete {label}",
  "Đạp xe": "Cycling",
  "Ngoài trời hoặc xe đạp tại chỗ": "Outdoor or stationary bike",
  "Chạy bộ": "Running",
  "Có thể nhập quãng đường hoặc tốc độ": "Enter distance or speed if available",
  "Chạy máy": "Treadmill",
  "Có thêm tốc độ và góc dốc": "Includes speed and incline",
  "Tập gym": "Gym workout",
  "Tạ, máy, circuit hoặc full-body": "Weights, machines, circuits, or full body",
  "Cường độ cao, nghỉ ngắn": "High intensity with short rests",
  "Bơi": "Swimming",
  "Bơi nhẹ đến bơi nhanh": "Easy to fast swimming",
  "Đi bộ nhanh": "Brisk walking",
  "Đi bộ ngoài trời hoặc máy": "Outdoor or treadmill walking",
  "Nhẹ, giãn cơ, phục hồi": "Light movement, mobility, and recovery",
  "Bài khác": "Other activity",
  "AI hỗ trợ nếu mô tả đủ rõ": "AI can help when the description is detailed",
  "Nhẹ": "Light",
  "Vừa": "Moderate",
  "Nặng": "Hard",
  "Rất nặng": "Very hard",
  "Ghi bài tập chi tiết": "Log workout details",
  "{calories} kcal từ workout": "{calories} kcal from workouts",
  "Thời lượng": "Duration",
  "Cường độ": "Intensity",
  "Quãng đường": "Distance",
  "Tốc độ": "Speed",
  "Góc dốc máy": "Treadmill incline",
  "Calo tự nhập": "Manual calories",
  "Ví dụ: tập gym lưng xô 45 phút, nghỉ 60 giây mỗi set; hoặc chạy máy 30 phút tốc độ 8km/h dốc 5%...": "Example: 45-minute back workout with 60-second rests, or 30 minutes on a treadmill at 8 km/h and 5% incline...",
  "Đang tính...": "Calculating...",
  "Tính & lưu": "Calculate & save",
  "Công thức mặc định dùng MET theo cân nặng, thời lượng và cường độ. Nếu nhập calo tự đo từ máy/đồng hồ, hệ thống sẽ dùng số đó; bài khác hoặc mô tả phức tạp có thể dùng AI để ước tính bảo thủ hơn.": "The default estimate uses MET, weight, duration, and intensity. If you enter calories measured by a machine or watch, that value is used; custom or complex activities may use AI for a conservative estimate.",
  "Bắt đầu miễn phí": "Start free",
  "Trở thành SVIP": "Become SVIP",
  "Phổ Biến Nhất": "Most Popular",
  "Cao Cấp Nhất": "Top Tier",
  "Không tải được dữ liệu gói": "Unable to load plan data",
  "Chọn gói phù hợp": "Choose the right plan",
  "Đầu tư cho": "Invest in your",
  "sức khỏe": "health",
  "của bạn": "",
  "Giá và quyền lợi được tải từ backend, không còn hard-code trong UI.": "Prices and benefits are loaded from the backend and kept consistent across NutriPath.",
  "Theo tháng": "Monthly",
  "Theo năm": "Annual",
  "tháng": "month",
  "Thanh toán bảo mật SSL": "Secure SSL payments",
  "Kích hoạt ngay lập tức": "Instant activation",
  "Câu hỏi thường gặp": "Frequently asked questions",
  "Bắt đầu ngay hôm nay": "Get started today",
  "Dùng thử 14 ngày miễn phí, không cần thẻ tín dụng": "Try it free for 14 days, no credit card required",
  "Dùng thử VIP": "Try VIP",
  "Chính sách quyền riêng tư": "Privacy Policy",
  "Trang này mô tả cách NutriPath thu thập, sử dụng và bảo vệ dữ liệu người dùng khi dùng ứng dụng, bao gồm đăng nhập bằng Google và Facebook qua Supabase Auth.": "This page explains how NutriPath collects, uses, and protects user data, including Google and Facebook sign-in through Supabase Auth.",
  "1. Dữ liệu NutriPath thu thập": "1. Data NutriPath collects",
  "Khi bạn đăng ký hoặc đăng nhập bằng email, Google hoặc Facebook, NutriPath có thể nhận tên hiển thị, email, ảnh đại diện công khai và mã định danh tài khoản từ nhà cung cấp đăng nhập.": "When you sign up or log in with email, Google, or Facebook, NutriPath may receive your display name, email, public profile photo, and account identifier from the sign-in provider.",
  "Khi bạn sử dụng ứng dụng, NutriPath lưu các dữ liệu bạn chủ động nhập như mục tiêu calo, chiều cao, cân nặng, tuổi, giới tính, mức độ vận động, nhật ký bữa ăn, đồ uống, công thức đã lưu và lịch sử chat dinh dưỡng.": "When you use the app, NutriPath stores data you provide, such as calorie goals, height, weight, age, gender, activity level, meal and drink logs, saved recipes, and nutrition chat history.",
  "2. Mục đích sử dụng dữ liệu": "2. How we use data",
  "Dữ liệu được dùng để tạo hồ sơ dinh dưỡng, hiển thị dashboard cá nhân, tính calo/macro ước lượng, lưu nhật ký bữa ăn và cá nhân hóa gợi ý healthy food.": "Data is used to build your nutrition profile, display your personal dashboard, estimate calories and macros, save meal logs, and personalize healthy food suggestions.",
  "Thông tin đăng nhập Google/Facebook chỉ dùng để xác thực tài khoản và liên kết với hồ sơ NutriPath của bạn.": "Google and Facebook sign-in information is used only to authenticate your account and link it to your NutriPath profile.",
  "3. Chia sẻ dữ liệu": "3. Data sharing",
  "NutriPath không bán dữ liệu cá nhân của người dùng.": "NutriPath does not sell user personal data.",
  "Dữ liệu có thể được xử lý bởi các dịch vụ hạ tầng cần thiết như Supabase, Render, Vercel hoặc nhà cung cấp AI để vận hành tính năng, nhưng chỉ trong phạm vi cần thiết cho sản phẩm.": "Data may be processed by essential infrastructure providers such as Supabase, Render, Vercel, or AI providers, only as needed to operate the product.",
  "4. Bảo mật": "4. Security",
  "API key, database password và cấu hình server không được lưu trong React frontend.": "API keys, database passwords, and server configuration are never stored in the React frontend.",
  "Các API bảo vệ dữ liệu cá nhân yêu cầu phiên đăng nhập hợp lệ. Dữ liệu nhạy cảm không được gửi sang AI nếu không cần thiết.": "APIs that protect personal data require a valid authenticated session. Sensitive data is not sent to AI unless necessary.",
  "5. Quyền của người dùng": "5. Your rights",
  "Bạn có thể yêu cầu xem, cập nhật hoặc xóa dữ liệu cá nhân của mình.": "You may request access to, correction of, or deletion of your personal data.",
  "Bạn có thể xem hướng dẫn xóa dữ liệu tại trang Xóa dữ liệu người dùng.": "You can find deletion instructions on the User Data Deletion page.",
  "6. Liên hệ": "6. Contact",
  "Nếu có câu hỏi về quyền riêng tư hoặc dữ liệu cá nhân, vui lòng liên hệ đội NutriPath qua email: support@nutripath.app.": "For questions about privacy or personal data, contact the NutriPath team at support@nutripath.app.",
  "Chính sách này có thể được cập nhật khi sản phẩm thay đổi. Ngày cập nhật gần nhất: 08/06/2026.": "This policy may be updated as the product evolves. Last updated: June 8, 2026.",
  "Xem hướng dẫn xóa dữ liệu": "View data deletion instructions",
  "Xóa dữ liệu người dùng": "User Data Deletion",
  "Trang này hướng dẫn người dùng NutriPath yêu cầu xóa dữ liệu cá nhân, bao gồm dữ liệu được tạo khi đăng nhập bằng Google hoặc Facebook qua Supabase Auth.": "This page explains how NutriPath users can request deletion of personal data, including data created through Google or Facebook sign-in via Supabase Auth.",
  "Cách yêu cầu xóa dữ liệu": "How to request data deletion",
  "Gửi email đến support@nutripath.app bằng email đã dùng để đăng nhập NutriPath.": "Email support@nutripath.app from the address you use to sign in to NutriPath.",
  "Tiêu đề email: Yêu cầu xóa dữ liệu NutriPath.": "Use the subject: NutriPath data deletion request.",
  "Trong nội dung, ghi rõ bạn muốn xóa tài khoản, nhật ký bữa ăn, lịch sử chat, dữ liệu Google/Facebook OAuth và các dữ liệu cá nhân liên quan.": "State that you want to delete your account, meal journal, chat history, Google/Facebook OAuth data, and related personal data.",
  "NutriPath sẽ xác minh quyền sở hữu tài khoản qua email đăng ký hoặc nhà cung cấp đăng nhập.": "NutriPath will verify account ownership through your registered email or sign-in provider.",
  "Sau khi xác minh, dữ liệu cá nhân sẽ được xóa khỏi hệ thống vận hành trong thời gian hợp lý, thường trong vòng 7 ngày làm việc.": "After verification, personal data will be removed from operational systems within a reasonable period, usually within 7 business days.",
  "Gửi yêu cầu xóa dữ liệu": "Send deletion request",
  "Dữ liệu sẽ được xóa": "Data that will be deleted",
  "Thông tin hồ sơ thành viên: tên, email, ảnh đại diện, mục tiêu calo và dữ liệu dinh dưỡng cá nhân.": "Member profile information: name, email, profile photo, calorie goals, and personal nutrition data.",
  "Nhật ký bữa ăn, đồ uống, món tự nấu, công thức đã lưu và báo cáo liên quan.": "Meal and drink logs, homemade dishes, saved recipes, and related reports.",
  "Lịch sử chat NutriBot AI, log an toàn AI gắn với tài khoản, và mapping đăng nhập Google/Facebook.": "NutriBot AI chat history, account-linked AI safety logs, and Google/Facebook login mappings.",
  "Phiên đăng nhập hiện tại của tài khoản trong ứng dụng.": "The account's current app sessions.",
  "Dữ liệu có thể được giữ lại": "Data that may be retained",
  "Dữ liệu bắt buộc phải giữ theo yêu cầu pháp lý, chống gian lận hoặc bảo mật có thể được lưu trong thời gian cần thiết.": "Data required for legal, fraud-prevention, or security purposes may be retained for as long as necessary.",
  "Dữ liệu đã được ẩn danh hoặc tổng hợp để phân tích chất lượng sản phẩm có thể không thể liên kết ngược về người dùng cụ thể.": "Anonymized or aggregated product analytics may no longer be linkable to a specific user.",
  "Nếu bạn chỉ muốn ngắt kết nối Google/Facebook khỏi NutriPath nhưng vẫn giữ tài khoản, hãy ghi rõ yêu cầu trong email. Bạn cũng có thể xóa quyền truy cập của NutriPath trong phần cài đặt tài khoản Google hoặc Facebook.": "If you only want to disconnect Google or Facebook while keeping your NutriPath account, state that clearly in your email. You can also revoke NutriPath access in your Google or Facebook account settings.",
  "Ngày cập nhật gần nhất: 08/06/2026. Trang chính sách quyền riêng tư:": "Last updated: June 8, 2026. Privacy policy:",
  "Giao dịch tại VNPAY thành công.": "The VNPAY transaction was successful.",
  "Giao dịch bị nghi ngờ bất thường và cần được kiểm tra.": "The transaction was flagged for review.",
  "Thẻ hoặc tài khoản chưa đăng ký dịch vụ Internet Banking.": "The card or account is not registered for Internet Banking.",
  "Thông tin xác thực giao dịch không đúng quá số lần cho phép.": "Transaction authentication failed too many times.",
  "Giao dịch đã hết thời gian chờ thanh toán.": "The payment session has expired.",
  "Thẻ hoặc tài khoản đang bị khóa.": "The card or account is locked.",
  "Mã OTP không chính xác.": "The OTP is incorrect.",
  "Bạn đã hủy giao dịch.": "You cancelled the transaction.",
  "Tài khoản không đủ số dư để thanh toán.": "The account has insufficient funds.",
  "Tài khoản đã vượt hạn mức giao dịch trong ngày.": "The account has exceeded its daily transaction limit.",
  "Ngân hàng đang bảo trì.": "The bank is undergoing maintenance.",
  "Thông tin thanh toán không đúng quá số lần cho phép.": "Payment information was entered incorrectly too many times.",
  "VNPAY chưa xác định được lỗi giao dịch.": "VNPAY could not determine the transaction error.",
  "Đang kiểm tra trạng thái giao dịch...": "Checking transaction status...",
  "Thanh toán thành công. Gói thành viên đã được kích hoạt trên tài khoản của bạn.": "Payment successful. Your membership has been activated.",
  "Giao dịch không thành công. Tài khoản chưa được nâng gói.": "The transaction failed. Your membership was not upgraded.",
  "Giao dịch PayOS đã bị hủy, hết hạn hoặc không thành công. Tài khoản chưa được nâng gói.": "The PayOS transaction was cancelled, expired, or failed. Your membership was not upgraded.",
  "{gateway} đã chuyển bạn về NutriPath. Hệ thống đang chờ xác nhận thanh toán từ máy chủ.": "{gateway} returned you to NutriPath. The system is waiting for server-side payment confirmation.",
  "Không tải được trạng thái giao dịch.": "Unable to load transaction status.",
  "Không tìm thấy mã đơn PayOS hợp lệ trong liên kết trả về.": "No valid PayOS order code was found in the return URL.",
  "Bạn đã hủy thanh toán PayOS. Gói thành viên chưa được kích hoạt.": "You cancelled the PayOS payment. The membership was not activated.",
  "Chữ ký phản hồi VNPAY không hợp lệ. NutriPath không cập nhật gói từ dữ liệu này.": "The VNPAY response signature is invalid. NutriPath did not update your membership.",
  "Không tìm thấy giao dịch tương ứng trong NutriPath.": "No matching transaction was found in NutriPath.",
  "Không thể xác minh kết quả thanh toán.": "Unable to verify the payment result.",
  "Thanh toán thành công": "Payment successful",
  "Đang xác minh giao dịch": "Verifying transaction",
  "Đang chờ {gateway} xác nhận": "Waiting for {gateway} confirmation",
  "Phản hồi không hợp lệ": "Invalid response",
  "Thanh toán chưa hoàn tất": "Payment not completed",
  "Mã giao dịch": "Transaction ID",
  "Kiểm tra lại": "Check again",
  "Xem gói thành viên": "View membership",
  "Quay lại thanh toán": "Back to checkout",
  "Về dashboard": "Go to dashboard",
  "Chọn tại VNPAY": "Choose on VNPAY",
  "ATM / ngân hàng": "ATM / bank account",
  "Thẻ quốc tế": "International card",
  "Không tải được dữ liệu gói.": "Unable to load plan data.",
  "Không lấy được báo giá.": "Unable to load the quote.",
  "Kích hoạt gói thành công": "Membership activated",
  "Thanh toán hôm nay": "Due today",
  "Tổng thanh toán": "Total payment",
  "Xem hồ sơ thành viên": "View member profile",
  "Quay về dashboard": "Back to dashboard",
  "Thanh toán bảo mật": "Secure payment",
  "Checkout gói thành viên": "Membership checkout",
  "Báo giá và kích hoạt gói được lấy trực tiếp từ backend, không còn là màn demo cứng.": "Quotes and membership activation come directly from the backend, not a static demo.",
  "Chọn gói": "Choose a plan",
  "Đang tải mô tả gói...": "Loading plan details...",
  "Chu kỳ thanh toán": "Billing cycle",
  "Hàng tháng": "Monthly",
  "Thanh toán linh hoạt theo tháng": "Flexible monthly billing",
  "Hàng năm": "Annual",
  "Tiết kiệm hơn với giá theo năm": "Save more with annual billing",
  "Dùng thử 7 ngày miễn phí": "7-day free trial",
  "Kích hoạt quyền VIP/SVIP trong 7 ngày, thanh toán hôm nay là 0đ.": "Activate VIP/SVIP access for 7 days with 0 VND due today.",
  "Đang dùng thử": "Trial enabled",
  "Bật dùng thử": "Enable trial",
  "Phương thức thanh toán": "Payment method",
  "Dùng thử không yêu cầu nhập thẻ. Bạn có thể thanh toán sau khi hết thời gian dùng thử.": "The trial does not require a card. You can subscribe after the trial ends.",
  "Bạn sẽ được chuyển sang PayOS để quét VietQR hoặc chọn phương thức ngân hàng được hỗ trợ. NutriPath không nhận hoặc lưu thông tin tài khoản ngân hàng và OTP.": "You will be redirected to PayOS to scan VietQR or choose a supported bank method. NutriPath does not receive or store bank account details or OTPs.",
  "Bạn sẽ được chuyển sang VNPAY Sandbox để nhập thông tin thanh toán. NutriPath không nhận hoặc lưu số thẻ, CVV và OTP.": "You will be redirected to VNPAY Sandbox to enter payment details. NutriPath does not receive or store card numbers, CVVs, or OTPs.",
  "Đang lấy mô tả gói...": "Loading plan details...",
  "Mã giảm giá": "Discount code",
  "Áp dụng": "Apply",
  "Đang lấy báo giá từ backend...": "Loading quote from the backend...",
  "12 tháng": "12 months",
  "1 tháng": "1 month",
  "Dùng thử {days} ngày": "{days}-day trial",
  "Giảm giá {code}": "Discount {code}",
  "Đang kích hoạt gói...": "Activating membership...",
  "Đang chuyển sang {gateway}...": "Redirecting to {gateway}...",
  "Kích hoạt dùng thử": "Activate trial",
  "Thanh toán qua {gateway}": "Pay with {gateway}",
  "NutriPath không lưu số thẻ, CVV, OTP hoặc dữ liệu ngân hàng nhạy cảm.": "NutriPath does not store card numbers, CVVs, OTPs, or sensitive banking data.",
  "Gói chỉ được kích hoạt sau khi webhook/IPN có chữ ký và số tiền hợp lệ.": "Membership is activated only after a signed webhook/IPN confirms the correct amount.",
  "Return URL chỉ hiển thị kết quả; không thể tự nâng gói bằng cách sửa URL.": "The return URL only displays status; editing it cannot upgrade a membership.",
  "Tài khoản của bạn đã được": "Your account has been",
  "kích hoạt dùng thử {days} ngày": "activated for a {days}-day trial",
  "nâng cấp": "upgraded",
  "lên": "to",
  "Quyền mới đã được bật ngay trên dashboard, hồ sơ thành viên và các tính năng liên quan.": "Your new benefits are now active across the dashboard, member profile, and related features.",
  "Không tải được báo cáo dinh dưỡng.": "Unable to load the nutrition report.",
  "Đã xuất báo cáo CSV thành công.": "CSV report exported successfully.",
  "Không xuất được báo cáo.": "Unable to export the report.",
  "Đang tải báo cáo...": "Loading report...",
  "Không có dữ liệu báo cáo.": "No report data is available.",
  "Báo cáo dinh dưỡng": "Nutrition report",
  "Theo dõi tiến trình thật của bạn": "Track your real progress",
  "Tổng hợp calo, macro, nước, vận động và món ăn từ nhật ký bữa ăn trong quyền lịch sử của gói hiện tại.": "Review calories, macros, water, activity, and foods from your meal journal within your plan's history window.",
  "{days} ngày": "{days} days",
  "Đang xuất...": "Exporting...",
  "Xuất CSV": "Export CSV",
  "Gói {tier} chỉ mở báo cáo trong {days} ngày gần nhất. Nâng cấp để xem dài hơn.": "The {tier} plan includes reports for the latest {days} days. Upgrade for a longer view.",
  "Xuất báo cáo là quyền SVIP. Bạn vẫn xem được phân tích trong {days} ngày của gói hiện tại.": "Report export is an SVIP benefit. You can still view analytics for the {days} days included in your current plan.",
  "Nâng cấp": "Upgrade",
  "Calo TB/ngày": "Avg. calories/day",
  "Ngày có ghi bữa": "Days with meals",
  "ngày": "days",
  "Đạt mục tiêu calo": "Calorie target met",
  "trong kỳ": "in range",
  "Nước TB/ngày": "Avg. water/day",
  "Calo theo ngày": "Daily calories",
  "Macro trung bình": "Average macros",
  "Fat": "Fat",
  "Chưa đủ dữ liệu macro.": "Not enough macro data.",
  "Calo theo bữa": "Calories by meal",
  "Calo": "Calories",
  "Món xuất hiện nhiều": "Most frequent foods",
  "{count} lần ghi": "Logged {count} times",
  "Chưa có món ăn nào trong kỳ báo cáo.": "No foods were logged during this report period.",
  "Nhận xét nhanh": "Quick insights",
  "Ít vận động": "Sedentary",
  "Ngồi văn phòng, ít hoặc không tập": "Desk-based lifestyle with little or no exercise",
  "Nhẹ nhàng": "Lightly active",
  "Tập nhẹ 1-3 ngày/tuần": "Light exercise 1-3 days/week",
  "Vừa phải": "Moderately active",
  "Tập vừa 3-5 ngày/tuần": "Moderate exercise 3-5 days/week",
  "Năng động": "Active",
  "Tập nặng 6-7 ngày/tuần": "Hard exercise 6-7 days/week",
  "Rất năng động": "Very active",
  "Tập rất nặng hoặc chơi thể thao cường độ cao": "Very hard exercise or high-intensity sports",
  "Bơi lội": "Swimming",
  "Cầu lông": "Badminton",
  "Gầy/thon": "Lean",
  "Cân đối": "Average",
  "Cơ bắp": "Muscular",
  "Đầy đặn": "Curvy",
  "Ngoại cỡ": "Large",
  "Đã lưu hồ sơ mới nhất và chạy AI Coach SVIP để phân tích mục tiêu.": "Your latest profile was saved and SVIP AI Coach analyzed your goals.",
  "Đã lưu hồ sơ dinh dưỡng mới nhất. NutriBot VIP có thể dùng dữ liệu này để tư vấn sát hơn.": "Your latest nutrition profile was saved. NutriBot VIP can now provide more relevant guidance.",
  "Đã lưu hồ sơ dinh dưỡng mới nhất vào tài khoản của bạn.": "Your latest nutrition profile was saved to your account.",
  "Bạn đang tính nhanh ở chế độ khách. Đăng nhập để lưu vào dashboard và hồ sơ cá nhân.": "You are using guest calculation mode. Log in to save this to your dashboard and profile.",
  "Không thể tính toán lúc này.": "Unable to calculate right now.",
  "Máy Tính Calo & Dinh Dưỡng": "Calorie & Nutrition Calculator",
  "Tính BMR, TDEE, macro bằng công thức Mifflin-St Jeor, có giới hạn an toàn và lưu snapshot mới nhất.": "Calculate BMR, TDEE, and macros with the Mifflin-St Jeor equation, safety limits, and your latest saved snapshot.",
  "Lần lưu gần nhất": "Last saved",
  "SVIP: sau khi tính, AI Coach sẽ phân tích mục tiêu calo, macro và bước hành động theo hồ sơ của bạn.": "SVIP: after calculation, AI Coach analyzes calorie goals, macros, and personalized action steps.",
  "Dashboard sẽ cập nhật theo dữ liệu mới nhất sau mỗi lần tính.": "Your dashboard updates with the latest data after each calculation.",
  "Đăng nhập để lưu kết quả vào dashboard và cho AI dùng về sau.": "Log in to save results to your dashboard and make them available to AI later.",
  "Thông tin cơ bản": "Basic information",
  "Giới tính": "Gender",
  "Nam": "Male",
  "Nữ": "Female",
  "Hình dáng cơ thể": "Body shape",
  "Mô phỏng theo dữ liệu nhập": "Visualization from your data",
  "BMI khoảng {bmi}. Hình này chỉ để trực quan hóa vóc dáng, không thay thế đo thành phần cơ thể.": "Approximate BMI {bmi}. This figure is only a visual aid and does not replace a body composition assessment.",
  "Tuổi": "Age",
  "tuổi": "years",
  "Cân nặng": "Weight",
  "Chiều cao": "Height",
  "Mức độ hoạt động": "Activity level",
  "Duy trì": "Maintain",
  "Tăng cân": "Gain weight",
  "Bài tập tham chiếu": "Reference exercise",
  "Loại bài tập": "Exercise type",
  "Đang tính và lưu...": "Calculating and saving...",
  "Tính Toán Ngay": "Calculate Now",
  "Sẵn sàng tính toán?": "Ready to calculate?",
  "Điền thông tin bên trái để xem kết quả chi tiết và lưu hồ sơ mới nhất của bạn.": "Complete the form to see detailed results and save your latest profile.",
  "Calo cơ bản": "Basal calories",
  "Tiêu thụ hằng ngày": "Daily expenditure",
  "Calo mục tiêu": "Calorie target",
  "Duy trì cân nặng": "Maintain weight",
  "{delta} so với TDEE": "{delta} vs. TDEE",
  "Độ tin cậy & giới hạn an toàn": "Confidence & safety limits",
  "Công thức": "Formula",
  "Kết quả là ước lượng và có thể thay đổi theo cơ địa, vận động và sức khỏe.": "Results are estimates and may vary with physiology, activity, and health.",
  "Phân chia dinh dưỡng đa lượng": "Macronutrient split",
  "Năng lượng": "Energy",
  "Macro": "Macros",
  "Thời điểm ăn": "Meal timing",
  "Bước hành động": "Action steps",
  "Bấm tính để AI Coach SVIP phân tích kết quả theo hồ sơ, mục tiêu và nhật ký bữa ăn mới nhất.": "Calculate to let SVIP AI Coach analyze your profile, goals, and latest meal journal.",
  "Nâng lên SVIP để AI phân tích mục tiêu calo, macro, thời điểm ăn và bước hành động cá nhân hóa sau mỗi lần tính.": "Upgrade to SVIP for personalized AI analysis of calories, macros, meal timing, and action steps after each calculation.",
  "Chỉ số BMI": "BMI",
  "BMI chỉ là chỉ số tham khảo nhanh từ chiều cao và cân nặng, không phản ánh đầy đủ tỷ lệ cơ, mỡ hay tình trạng sức khỏe.": "BMI is a quick reference based on height and weight and does not fully reflect muscle, body fat, or health status.",
  "Calo đốt khi tập": "Exercise calories",
  "{exercise} trong {minutes} phút": "{exercise} for {minutes} minutes",
  "Tương đương khoảng {grams}g chất béo đốt cháy.": "Equivalent to approximately {grams} g of fat energy.",
  "Dễ": "Easy",
  "Khó": "Hard",
  "Tất cả": "All",
  "Không tải được công thức": "Unable to load recipes",
  "Không tạo được công thức cá nhân hóa": "Unable to create a personalized recipe",
  "Công thức được tải trực tiếp từ backend": "Recipes are loaded directly from the backend",
  "Tìm công thức, nguyên liệu...": "Search recipes or ingredients...",
  "Đang tải...": "Loading...",
  "Tìm thấy": "Found",
  "công thức": "recipes",
  "Công Thức Cá Nhân Hóa Do AI Tạo Ra": "AI-Generated Personalized Recipes",
  "AI tạo công thức riêng cho mục tiêu, thời điểm ăn, nguyên liệu sẵn có, khối lượng từng món, macro và lưu ý an toàn.": "AI creates a recipe for your goal, meal timing, available ingredients, precise quantities, macros, and safety notes.",
  "Mở khóa SVIP": "Unlock SVIP",
  "Ví dụ: Tôi muốn bữa trưa giảm mỡ, nhiều protein, có ức gà và khoai lang, nấu trong 25 phút...": "Example: I want a high-protein fat-loss lunch with chicken breast and sweet potato, ready in 25 minutes...",
  "Nếu thông tin chưa đủ, AI sẽ hỏi thêm vài câu trước khi tạo công thức.": "If details are missing, AI will ask a few follow-up questions before creating the recipe.",
  "Tạo công thức từ câu trả lời": "Create recipe from answers",
  "Tạo công thức AI": "Create AI recipe",
  "Tính năng này chỉ dành cho SVIP vì AI cần dùng hồ sơ dinh dưỡng nâng cao và lịch sử ăn uống để cá nhân hóa rõ hơn.": "This feature is for SVIP members because AI uses advanced nutrition profile data and meal history for deeper personalization.",
  "Gói Free chỉ xem {limit} công thức đầu tiên.": "The Free plan can view the first {limit} recipes.",
  "Hiện có {count} công thức phù hợp với bộ lọc. Nâng cấp VIP hoặc SVIP để mở toàn bộ kho công thức.": "There are {count} recipes matching this filter. Upgrade to VIP or SVIP to unlock the full library.",
  "Mở khóa VIP": "Unlock VIP",
  "Công thức AI đã lưu": "Saved AI recipes",
  "Những công thức SVIP AI đã tạo sẽ nằm ở đây để xem lại sau khi đăng nhập.": "Recipes created by SVIP AI are saved here for later viewing.",
  "{count} món": "{count} recipes",
  "người": "servings",
  "Xơ": "Fiber",
  "Không tìm thấy công thức phù hợp": "No matching recipes found",
  "Thử tìm kiếm với từ khóa khác": "Try a different search term",
  "kcal/phần": "kcal/serving",
  "người ăn": "servings",
  "Thời gian ăn": "Recommended time",
  "Bữa": "Meal",
  "Nguyên liệu": "Ingredients",
  "Thông tin dinh dưỡng": "Nutrition facts",
  "Carbohydrate": "Carbohydrates",
  "Chất xơ": "Fiber",
  "Hướng dẫn nấu chi tiết": "Detailed cooking instructions",
  "Công thức AI được trình bày theo từng thao tác, thời lượng, cách canh lửa và dấu hiệu món đã đạt.": "AI recipes explain each action, timing, heat level, and signs that the dish is ready.",
  "Làm theo thứ tự từng bước để giữ đúng hương vị, kết cấu và khẩu phần.": "Follow each step in order to preserve flavor, texture, and portion size.",
  "Lưu ý riêng": "Personal notes",
  "Tổng quan": "Overview",
  "Hoạt động": "Activity",
  "Cài đặt": "Settings",
  "Cân bằng": "Balanced",
  "Mặn/đậm vị": "Savory",
  "Món gia đình": "Family meals",
  "Không quá healthy": "Comfort food",
  "Việt": "Vietnamese",
  "Á": "Asian",
  "Âu": "Western",
  "Nhật": "Japanese",
  "Hàn": "Korean",
  "Không xác định": "Unknown",
  "Đang hoạt động": "Active",
  "Không tải được hồ sơ thành viên": "Unable to load member profile",
  "Đang tải hồ sơ thành viên...": "Loading member profile...",
  "Ngày thành viên": "Member days",
  "Công thức đã lưu": "Saved recipes",
  "cuộc hội thoại": "conversations",
  "Calo đã theo dõi": "Tracked calories",
  "kcal tổng": "total kcal",
  "Tên và email không được để trống.": "Name and email are required.",
  "Mục tiêu calo nên nằm trong khoảng 1200-5000 kcal/ngày.": "The calorie goal must be between 1,200 and 5,000 kcal/day.",
  "Mục tiêu nước nên nằm trong khoảng 500-5000ml/ngày.": "The water goal must be between 500 and 5,000 ml/day.",
  "Cân nặng nên nằm trong khoảng 30-250kg.": "Weight must be between 30 and 250 kg.",
  "Đã lưu cài đặt hồ sơ.": "Profile settings saved.",
  "Không lưu được cài đặt hồ sơ.": "Unable to save profile settings.",
  "Mua gói từ": "Member since",
  "Hết hạn": "Expires",
  "Gia hạn": "Renew",
  "Lên SVIP": "Upgrade to SVIP",
  "Thời gian còn lại": "Time remaining",
  "{remaining}/{total} ngày": "{remaining}/{total} days",
  "Thông báo của bạn": "Your notifications",
  "{count} thông báo chưa đọc từ backend.": "{count} unread notifications from the backend.",
  "Đánh dấu tất cả đã đọc": "Mark all as read",
  "Đã đọc": "Read",
  "Chưa có thông báo nào.": "No notifications yet.",
  "Cài đặt hồ sơ": "Profile settings",
  "Các thay đổi được lưu vào backend và đồng bộ lại toàn app.": "Changes are saved to the backend and synced across the app.",
  "Mục tiêu calo/ngày": "Daily calorie goal",
  "Mục tiêu nước/ngày (ml)": "Daily water goal (ml)",
  "Hồ sơ cơ thể & khẩu vị": "Body & food preferences",
  "Dữ liệu này giúp dashboard mô phỏng cơ thể, theo dõi cân nặng và cho AI tránh món dị ứng.": "This data helps visualize body shape, track weight, and keep allergens out of AI suggestions.",
  "Phong cách ăn": "Eating style",
  "Cân nặng hiện tại": "Current weight",
  "Cân nặng mục tiêu": "Target weight",
  "Nền ẩm thực ưu tiên": "Preferred cuisines",
  "Món dị ứng/cần tránh": "Allergies / foods to avoid",
  "Ví dụ: tôm, đậu phộng, sữa...": "Example: shrimp, peanuts, milk...",
  "Món không thích": "Disliked foods",
  "Ví dụ: hành sống, nội tạng...": "Example: raw onion, organ meats...",
  "Ghi chú khẩu vị": "Taste notes",
  "Ví dụ: thích cay nhẹ, ít dầu, món gia đình...": "Example: mildly spicy, less oil, family-style meals...",
  "Đang lưu...": "Saving...",
  "Lưu cài đặt": "Save settings",
  "Quyền lợi của bạn": "Your benefits",
  "Nâng lên SVIP để mở khóa AI Coach và thêm quyền lợi": "Upgrade to SVIP to unlock AI Coach and more benefits",
  "Quyền gói được lấy từ backend sau checkout.": "Plan benefits are loaded from the backend after checkout.",
  "Lịch sử thanh toán": "Payment history",
  "Thu gọn": "Collapse",
  "Ngày": "Date",
  "Gói": "Plan",
  "Số tiền": "Amount",
  "Trạng thái": "Status",
  "Hóa đơn": "Invoice",
  "Chưa có giao dịch nào.": "No transactions yet.",
};

interface LanguageContextValue {
  language: AppLanguage;
  locale: "vi-VN" | "en-US";
  setLanguage: (language: AppLanguage) => void;
  toggleLanguage: () => void;
  t: (vietnameseText: string, values?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

function getStoredLanguage(): AppLanguage {
  if (typeof window === "undefined") return "vi";
  return window.localStorage.getItem(STORAGE_KEY) === "en" ? "en" : "vi";
}

function interpolate(message: string, values: Record<string, string | number> = {}) {
  return message.replace(/\{(\w+)\}/g, (match, key) => (
    Object.prototype.hasOwnProperty.call(values, key) ? String(values[key]) : match
  ));
}

function translateDynamicEnglish(text: string) {
  const direct = englishMessages[text];
  if (direct) return direct;

  const step = text.match(/^Bước\s+(\d+)$/i);
  if (step) return `Step ${step[1]}`;

  const greeting = text.match(/^Xin chào,\s*(.+)$/i);
  if (greeting) return `Hello, ${greeting[1]}`;

  return text;
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<AppLanguage>(() => getStoredLanguage());

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dataset.language = language;
  }, [language]);

  const value = useMemo<LanguageContextValue>(() => {
    const setLanguage = (nextLanguage: AppLanguage) => {
      window.localStorage.setItem(STORAGE_KEY, nextLanguage);
      setLanguageState(nextLanguage);
    };

    return {
      language,
      locale: language === "en" ? "en-US" : "vi-VN",
      setLanguage,
      toggleLanguage: () => setLanguage(language === "vi" ? "en" : "vi"),
      t: (vietnameseText, values) => interpolate(
        language === "en" ? translateDynamicEnglish(vietnameseText) : vietnameseText,
        values,
      ),
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const value = useContext(LanguageContext);
  if (!value) throw new Error("useLanguage must be used inside LanguageProvider");
  return value;
}
